
[functions.listar-usuarios-para-admin]
enabled = true
verify_jwt = true
import_map = "./functions/listar-usuarios-para-admin/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/listar-usuarios-para-admin/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/listar-usuarios-para-admin/*.html" ]

[functions.send-report]
enabled = true
verify_jwt = true
import_map = "./functions/send-report/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-report/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-report/*.html" ]
